package com.andersenlab.etalon.infoservice.util.enums;

public enum EmailType {
  CONFIRMATION,
  REGISTRATION,
  EMAIL_MODIFY_CONFIRMATION,
  SHARING_TRANSFER_RECEIPT,
  CONFIRMATION_STATEMENT,
  PASSWORD_RESET_CONFIRMATION
}
