version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK_RELATIVE: 0.8
    ports:
      - "5672:5672"
      - "15672:15672"

  deposit-service:
    hostname: deposit-service
    container_name: deposit-service
    build:
      context: ..
      dockerfile: Dockerfile
    image: deposit-service
    restart: always
    ports:
      - "9005:9005"
    environment:
      SPRING_DATASOURCE_USERNAME: $AND_DB_USER
      SPRING_DATASOURCE_PASSWORD: $AND_DB_PASS
      SPRING_DATASOURCE_URL: $AND_DB_URL
      SPRING_LIQUIBASE_USERNAME: $AND_DB_USER
      SPRING_LIQUIBASE_PASSWORD: $AND_DB_PASS
      SPRING_LIQUIBASE_URL: $AND_DB_URL
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: $AND_EUREKA_URL
    networks:
      - amusic2-etalon-net

networks:
  amusic2-etalon-net:
    name: amusic2-local
    driver: bridge